### ISSUE TITLE
Taking A lot of time to load

### ISSUE THREAD

**Issue by roalts** [Codeminators/byldafarm#1]
When we press back and come to calculate profit fragment, it keeps on loading doesn't move to the next fragment.

**Comment by ananay** [comment]
Dude the app gets stuck in an infinite loop once we press back.

**Comment by prempalsingh** [comment]
fixed

**Comment by prempalsingh** [comment]
Sab fix karega re tera faisal

Dude the app gets stuck in an infinite loop once we press back.
